
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql-security:
        applies-to: security-updates
        patterns:
          - "github/codeql-action/*"
      codeql-version:
        applies-to: version-updates
        patterns:
          - "github/codeql-action/*"
  - package-ecosystem: "nuget"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      microsoft-identitymodel-security:
        applies-to: security-updates
        patterns:
          - "Microsoft.IdentityModel.*"
      microsoft-identitymodel-version:
        applies-to: version-updates
        patterns:
          - "Microsoft.IdentityModel.*"
      microsoft-extensions-logging-security:
        applies-to: security-updates
        patterns:
          - "Microsoft.Extensions.Logging"
          - "Microsoft.Extensions.Logging.*"
      microsoft-extensions-logging-version:
        applies-to: version-updates
        patterns:
          - "Microsoft.Extensions.Logging"
          - "Microsoft.Extensions.Logging.*"
  - package-ecosystem: "uv"
    directories:
      - "/Diff"
      - "/TldRegexUpdater"
    schedule:
      interval: "weekly"
