
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
  - package-ecosystem: "nuget"
    directories:
      - "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directories:
      - "/Diff"
      - "/TldRegexUpdater"
    schedule:
      interval: "weekly"
