name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  buildtest:
    name: Test build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Build with dotnet
        run: dotnet build --configuration Debug
      - name: Test with dotnet
        run: dotnet test --collect:"XPlat Code Coverage;Format=lcov"
      - name: Collect reports
        id: reports
        run: |
            mkdir -p ./CollectedTestResults
            for x in `find . -path ./CollectedTestResults -prune -o -name 'coverage.info' -print`; do
                echo $x
                cp $x ./CollectedTestResults/`basename $(dirname $(dirname $(dirname ${x})))`.coverage.lcov
            done
      - name: Report coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
