name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run tests on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1
        with:
          dotnet-version: '9.0.x'
      - name: Test with dotnet
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.UseSourceLink=true
      - name: Collect reports
        run: |
            mkdir -p ./CollectedTestResults
            for x in `find . -path ./CollectedTestResults -prune -o -name 'coverage.cobertura.xml' -print`; do
                echo $x
                cp $x ./CollectedTestResults/`basename $(dirname $(dirname $(dirname ${x})))`.coverage.cobertura.xml
            done
      - name: Generate code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@049f7ec958c672fd31d5cc1cb01622dc8d2e23ab
        with:
          reports: ./CollectedTestResults/*.coverage.cobertura.xml
          targetdir: coveragereport
          reporttypes: Html;MarkdownSummaryGithub
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
            name: coveragereport
            path: ./coveragereport/
      - name: Publish coverage in build summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
  altconditiontest:
    name: Run tests with alternate conditions on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        timezone: ['UTC', 'America/New_York', 'Europe/London', 'Asia/Tokyo']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1
        with:
          dotnet-version: '9.0.x'
      - name: Test with dotnet
        run: dotnet test
        env:
          TZ: ${{ matrix.timezone }}
